export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_LOADING = 'FETCH_USER_LOADING';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
export const FETCH_REPOS_LOADING = 'FETCH_REPOS_LOADING';
export const FETCH_REPOS_FAILED = 'FETCH_REPOS_FAILED';
export const SAVE_USER = 'SAVE_USE';
export const DELETE_USER = 'DELETE_USER';
